name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - wandb=0.13.10
  - mlflow=2.2.2
  - hydra-core=1.0.6
  - pandas=1.5.3
  - scikit-learn=1.2.1
  - matplotlib==3.7.1
  - plotly==5.13.1
  - pillow=9.4.0
  - pytest=7.2.2
  - scipy=1.10.1
  - pyarrow=11.0.0
  - pip=23.0.1
  - pip:
      - hydra-joblib-launcher==1.2.0
      - omegaconf==2.2.3
